services:
    # Base de datos para Auth (Django)
    db_auth:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: auth_db
            POSTGRES_USER: user_auth
            POSTGRES_PASSWORD: password_auth
        ports:
            - "5433:5432" # Puerto externo 5433 para no chocar con el otro Postgres

    # Base de datos para Reservas (NestJS)
    db_reservations:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: reservations_db
            POSTGRES_USER: user_res
            POSTGRES_PASSWORD: password_res
        ports:
            - "5434:5432" # Puerto externo 5434

    # Base de datos para Eventos (NestJS)
    db_events:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_DATABASE: events_db
        ports:
            - "27017:27017"

    # Broker para Comunicación (Redis)
    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"

volumes:
    postgres_auth_data:
    postgres_res_data:
    mongo_events_data: